### ISSUE TITLE
The method or operation is not implemented

### ISSUE THREAD

**Issue by flcdrg** [madskristensen/TrailingWhitespace#20]
Upgraded to the latest version, running on VS2013 Update 4.

Went to open an .aspx page and was greeted with 'An exception has been encountered. This may be caused by an extension' dialog.

Relevant lines from ActivityLog.xml are:

```xml
  <entry>
    <record>1109</record>
    <time>2015/04/22 02:48:22.702</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NotImplementedException: The method or operation is not implemented.&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.SecondaryVsTextBufferAdapter.Microsoft.VisualStudio.Shell.Interop.IPersistFileFormat.GetCurFile(String&amp; ppszFilename, UInt32&amp; pnFormatIndex)&#x000D;&#x000A;   at TrailingWhitespace.TrailingClassifierProvider.GetFileName(ITextBuffer buffer) in c:\projects\trailingwhitespace\src\Classifier\ClassifierProvider.cs:line 41&#x000D;&#x000A;   at TrailingWhitespace.TrailingClassifierProvider.GetClassifier(ITextBuffer textBuffer) in c:\projects\trailingwhitespace\src\Classifier\ClassifierProvider.cs:line 0&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass1`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)</description>
  </entry>
  <entry>
    <record>1110</record>
    <time>2015/04/22 02:48:22.704</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.NotImplementedException: The method or operation is not implemented.&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.SecondaryVsTextBufferAdapter.Microsoft.VisualStudio.Shell.Interop.IPersistFileFormat.GetCurFile(String&amp; ppszFilename, UInt32&amp; pnFormatIndex)&#x000D;&#x000A;   at TrailingWhitespace.TrailingClassifierProvider.GetFileName(ITextBuffer buffer) in c:\projects\trailingwhitespace\src\Classifier\ClassifierProvider.cs:line 41&#x000D;&#x000A;   at TrailingWhitespace.TrailingClassifierProvider.GetClassifier(ITextBuffer textBuffer) in c:\projects\trailingwhitespace\src\Classifier\ClassifierProvider.cs:line 0&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.&lt;&gt;c__DisplayClass1`1.&lt;CreateTagger&gt;b__0(IClassifierProvider provider)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)</description>
  </entry>
```

**Comment by madskristensen** [comment]
A new release is going out in a few minutes with this fix

**Comment by gcastre** [comment]
Hello,

I'm using Visual studio 2015 Update 1 CTP and TrailingWhitespace 2.0.57. I had the same issue when I opened my solution (seems like a long time exception, but the first time I saw it in the output panel):

```c#
03/11/2015 09:10:26: 
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudio.Editor.Implementation.SecondaryVsTextBufferAdapter.Microsoft.VisualStudio.Shell.Interop.IPersistFileFormat.GetCurFile(String& ppszFilename, UInt32& pnFormatIndex)
   at TrailingWhitespace.TrailingClassifierProvider.GetFileName(ITextBuffer buffer) in c:\projects\trailingwhitespace\src\Classifier\ClassifierProvider.cs:line 52
```

**Comment by gcastre** [comment]
This exception is still happening with the update 1 of Visual Studio.

Can you push the nightly build (2.0.58) to the gallery ?

**Comment by madskristensen** [comment]
Done
