### ISSUE TITLE
OutOfMemoryException

### ISSUE THREAD

**Issue by gooseserbus** [madskristensen/TrailingWhitespace#25]
### Installed product versions
- Visual Studio: MS VS Professional 2012 11.0.61219.00 Update 5
- This extension: 2.3.66

### Description
Had an out of memory exception with the following call stack from the log:

    System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
    at Microsoft.VisualStudio.Text.Implementation.BinaryStringRebuilder.GetText(Span span)
    at Microsoft.VisualStudio.Text.Implementation.TextSnapshot.GetText(Span span)
    at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.GetText()
    at TrailingWhitespace.FileHelpers.IsFileSupported(ITextBuffer buffer) in c:\projects\trailingwhitespace\src\Helpers\FileHelpers.cs:line 35
    at TrailingWhitespace.TrailingClassifierProvider.GetClassifier(ITextBuffer textBuffer) in c:\projects\trailingwhitespace\src\Classifier\ClassifierProvider.cs:line 19
    at Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTaggerProvider.<>c__DisplayClass1`1.<CreateTagger>b__0(IClassifierProvider provider)
    at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.InvokeMatchingFactories[TExtensionInstance,TExtensionFactory,TMetadataView](IEnumerable`1 lazyFactories, Func`2 getter, IContentType dataContentType, Object errorSource)

### Steps to recreate
Not sure exactly what caused this, I'd been debugging several instances of an application and shut them down, then VS was acting really slow and eventually popped up a message box telling me to check the log.

**Comment by gooseserbus** [comment]
https://blogs.msdn.microsoft.com/noahric/2010/07/13/qa-itextsnapshot-gettext/

So I guess this was because I didn't have a contiguous free memory block which was big enough.

**Comment by madskristensen** [comment]
Yeah, I know how to fix this now. Thanks

**Comment by madskristensen** [comment]
This should now be fixed and can be tested in the latest CI build found here http://vsixgallery.com/extension/4c1a78e6-e7b8-4aa9-8812-4836e051ff6d/

**Comment by gooseserbus** [comment]
Thanks, I've updated to 2.3.71.
