### ISSUE TITLE
Installer does not work for 2017-RC-26009

### ISSUE THREAD

**Issue by iwhp** [madskristensen/TrailingWhitespace#38]
### Installed product versions
- Visual Studio: 2017 Enterprise RC 26009
- This extension: 2.5.82

### Description
VS2017 does indicated an update, but the installer does not work.

14.12.2016 10:49:33 - Beginning to install extension to Microsoft Visual Studio Enterprise 2017 RC...
14.12.2016 10:49:33 - Upgrading 'Trailing Whitespace Visualizer', version 2.5.81 to version 2.5.82.
14.12.2016 10:49:33 - Install Error : System.IO.FileNotFoundException: Unable to find the specified file.

### Steps to recreate
1. Start VS 2017
2. TOOLS/Extensions and Updates
3. Updates
4. Select Trailing Whitespace Visualizer
5. Close VS 2017
6. Installer starts and failes

### Expected behavior
Should install

### Addional information
I downloaded the VSIX packages and installed from there.
VS 2015 is update, but VS 2017 is not recognized

**Comment by xt0rted** [comment]
I'm having the same issue. It's also failing to update the [File Icons](https://github.com/madskristensen/FileIcons) and [Syntax Highlighting Pack](https://github.com/madskristensen/TextmateBundleInstaller) extensions.

```
12/19/2016 6:44:45 PM - Beginning to install extension to Microsoft Visual Studio Enterprise 2017 RC...
12/19/2016 6:44:45 PM - Upgrading 'Trailing Whitespace Visualizer', version 2.5.81 to version 2.5.82.
12/19/2016 6:44:45 PM - Install Error : System.IO.FileNotFoundException: Unable to find the specified file.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
```

**Comment by madskristensen** [comment]
This should have been fixed by the latest updates to Visual Studio 2017 RC

**Comment by iwhp** [comment]
Thankx for your great work! Looking forward to VS 2017 ;-)
